### ISSUE TITLE
EMLP Discussion Update

### ISSUE THREAD

**Issue by whitead** [whitead/dmol-book#36]
Number of constant values in equivariant linear basis is not the same as number of free parameters (?) Need to check on this. 

https://github.com/mfinzi/equivariant-MLP/issues/14#issuecomment-898676826

**Comment by whitead** [comment]
![image](https://user-images.githubusercontent.com/908389/129410858-e36d4fd2-16db-4265-a006-c2d44f6af2dd.png)

**Comment by mfinzi** [comment]
Yes this can be true for non permutation representations and is also why for visualization the recommendation for non permutation representations is to use `vis(repin,repout,cluster=False)` otherwise the visualization can be misleading. It may be possible to add functionality to vis to check whether the rep is a permutation and set cluster accordingly.

A good example is ```python (V**3)(SO(3))``` which has the equivariant solution εᵢⱼₖ (the levi civita tensor) ![image](https://user-images.githubusercontent.com/12687085/129422932-fcad1612-11ca-479e-9dbf-253af7f2818a.png). It forms a one dimensional equivariant subspace but has both positive and negative entries.

**Comment by whitead** [comment]
Fixed by 700c749
