### ISSUE TITLE
string vs. graph representation

### ISSUE THREAD

**Issue by kjappelbaum** [whitead/dmol-book#66]
I think you mention that there is currently no paper on this and I think i agree with that. 
A nice hint is the guacamol leaderboard https://www.benevolent.com/guacamol and [when we tested on SELFIES](https://arxiv.org/abs/2102.00700) we also didn't find it outperform the graph based models. Clearly it is also related with the modeling but as you write I also think that the representation matters. 

Would be interesting to do a proper benchmark, where one also considers the latent space of a model trained on string-based representation (e.g., a VAE, maybe trained jointly with some properties)

**Comment by kjappelbaum** [comment]
(and one nice reference for the symmetry and GNN chapter is probably https://geometricdeeplearning.com/)

**Comment by whitead** [comment]
I think your referring to [this section](https://dmol.pub/dl/gnn.html#do-we-need-graphs) at end of GNNs. That is a little old, I wrote a more nuanced discussion this [summer](https://dmol.pub/dl/NLP.html#selfies) specifically about SELFIES.

After thinking about it more since I wrote that - a GNN has atom permutation equivariance so you can predict things per atom/bond. A string is atom invariant - you can only predict per molecule properties. The advantages of the string representation are implementations are easier, few architecture choices (relative to GNN), and generation is trivial. As far as accuracy, I agree yes it's not clear. There is a persistent folklore that SMILES is worse than graph because there are long-range effects (closing braces) that are difficult to capture, but I've never seen convincing evidence. Definitely need to update the GNN section. Thanks for bringing this up!

**Comment by whitead** [comment]
Gonna call this good for now, but will revisit once SELFIES perspective is done and there is a bit more lit on this topic.
